### ISSUE TITLE
这个是不是咏春大师2量化版才可以？

### ISSUE THREAD

**Issue by davidwang558** [vnpy/vnpy_voltrader#2]
我用的咏春大师2，一直报错：
```
2024-10-13 15:58:09	交易接口认证失败
2024-10-13 15:58:12	行情接口认证失败
请交易接口认证成功后，再使用该功能
Traceback (most recent call last):
  File "C:\veighna_studio\lib\site-packages\vnpy\trader\ui\mainwindow.py", line 277, in open_widget
2024-10-13 15:58:12	    widget = widget_class(self.main_engine, self.event_engine)
  File "C:\veighna_studio\lib\site-packages\vnpy_ctabacktester\ui\widget.py", line 56, in __init__
    self.backtester_engine.init_engine()
  File "C:\veighna_studio\lib\site-packages\vnpy_ctabacktester\engine.py", line 71, in init_engine
    self.init_datafeed()
  File "C:\veighna_studio\lib\site-packages\vnpy_ctabacktester\engine.py", line 77, in init_datafeed
    result: bool = self.datafeed.init(self.write_log)
  File "C:\veighna_studio\lib\site-packages\vnpy_voltrader\voltrader_datafeed.py", line 69, in init
2024-10-13 15:58:12	    self.query_symbols()
  File "C:\veighna_studio\lib\site-packages\vnpy_voltrader\voltrader_datafeed.py", line 78, in query_symbols
    symbols: list = self.api.getallsymbol(exchange=exchange_str)
  File "C:\veighna_studio\lib\site-packages\icetcore\api.py", line 779, in getallsymbol
    if self.quoteobj.eventobj.symbollistready:
AttributeError: 'NoneType' object has no attribute 'eventobj'
```

**Comment by vnpy** [comment]
是的，需要额外付费开通API权限的版本

**Comment by davidwang558** [comment]
了解了 谢谢哈
